DonationManagementSystem/urls.py
from django.contrib import admin
from django.urls import path
from donation.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('all_logins',all_logins,name='all_logins'),
    path('donor_login',donor_login,name='donor_login'),
    path('charfo_login',charfo_login,name='charfo_login'),
    path('admin_login',admin_login,name='admin_login'),
    path('donor_reg',donor_reg,name='donor_reg'),
    path('charfo_reg',charfo_reg,name='charfo_reg'),
    path('donor_home',donor_home,name='donor_home'),
    path('logout/',Logout,name='logout'),
    path('donate_now',donate_now,name='donate_now')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

donation/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Donor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact =models.CharField(max_length=15,null=True)
    address =models.CharField(max_length=300,null=True)
    userpic =models.FileField(null=True)
    regdate =models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class CharFound(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact =models.CharField(max_length=15,null=True)
    address =models.CharField(max_length=300,null=True)
    userpic =models.FileField(null=True)
    idpic =models.FileField(null=True)
    aboutme =models.CharField(max_length=300,null=True)
    status =models.CharField(max_length=20,null=True)
    regdate =models.DateTimeField(auto_now_add=True)
    adminremark =models.CharField(max_length=20,null=True)
    updationdate=models.DateField(null=True)
    def __str__(self):
        return self.user.username

class DonationArea(models.Model):
    areaname =models.CharField(max_length=15,null=True)
    description =models.CharField(max_length=300,null=True)
    creationdate =models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.areaname

class Donation(models.Model):
    donor = models.ForeignKey(Donor,on_delete=models.CASCADE)
    donationname = models.CharField(max_length=100,null=True)
    donationpic = models.FileField(null=True)
    collectionloc = models.CharField(max_length=300, null=True)
    description = models.CharField(max_length=300,null=True)
    status = models.CharField(max_length=50,null=True)
    donationdate = models.DateTimeField(auto_now_add=True)
    adminremark = models.CharField(max_length=300,null=True)
    volunteer = models.ForeignKey(CharFound,on_delete=models.CASCADE)
    donationarea = models.ForeignKey(DonationArea, on_delete=models.CASCADE)
    updationdate = models.DateField(null=True)
    def __str__(self):
        return self.id

class Gallery(models.Model):
    donation = models.ForeignKey(Donation,on_delete=models.CASCADE)
    deliverypic = models.FileField(null=True)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.id

donation/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,login,logout
from .models import *

# Create your views here.

def index(request):
    return render(request, 'index.html')

def all_logins(request):
    return render(request, 'all_logins.html')

def donor_login(request):
    if request.method == 'POST':
        u = request.POST['emailid']
        p = request.POST['pwd']
        user = authenticate(username = u, password = p)
        if user:
            login(request,user)
            error = "no"
        else:
            error = "yes"
    return render(request, 'donor_login.html', locals())

def charfo_login(request):
    return render(request, 'charfo_login.html')

def admin_login(request):
    return render(request, 'admin_login.html')

def donor_reg(request):
    error = ""
    if request.method == "POST":
        fn =request.POST['firstname']
        ln =request.POST['lastname']
        em =request.POST['email']
        contact =request.POST['contact']
        pwd =request.POST['pwd']
        userpic =request.FILES['userpic']
        address =request.POST['address']
        
        
        try:
            user = User.objects.create_user(first_name = fn,last_name=ln,username=em,password=pwd )
            Donor.objects.create(user=user, contact=contact,userpic=userpic,address=address)
            error="no"
        except:
            error="yes"
    return render(request, 'donor_reg.html',locals())

def charfo_reg(request):
    error = ""
    if request.method == "POST":
        fn =request.POST['firstname']
        ln =request.POST['lastname']
        em =request.POST['email']
        contact =request.POST['contact']
        pwd =request.POST['pwd']
        userpic =request.FILES['userpic']
        idpic =request.FILES['idpic']
        address =request.POST['address']
        
        
        try:
            user = User.objects.create_user(first_name = fn,last_name=ln,username=em,password=pwd )
            CharFound.objects.create(user=user, contact=contact,userpic=userpic,idpic=idpic,address=address)
            error="no"
        except:
            error="yes"
    return render(request, 'charfo_reg.html', locals())

def donor_home(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    return render(request, 'donor_home.html')

def donate_now(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    
    return render(request, 'donate_now.html')


def Logout(request):
    logout(request)
    return redirect('index')





    

donation/templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
</head>
<body style="background-image: url({% static 'images/depositphotos_55150353-stock-photo-admin-cubics.jpg' %});">
    {% include 'navigation.html' %}
    <hr class="mt-0">
    <div class="row">
        <div class="col-lg-5 m-auto">
            <div class="card mt-5 bg-dark">
                <div class="card-title text-center mt-3">
                    <img src="{% static 'images/2476166.jpg' %}" alt="" width="150" height="150">
                    <h2 style="color: aliceblue;">Admin Login</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user fa-2x"></i>
                                </span>
                            </div>
                            <input type="name" name="username" class="form-control py-4" placeholder="Username">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-lock fa-2x"></i>
                                </span>
                            </div>
                            <input type="password" name="pwd" class="form-control py-4" placeholder="password">
                        </div>
                        <input type="submit" value="login" class="btn btn-success px-5">
                        <a href="{% url 'index' %}" class="float-right text-white mt-2">Go back to Home</a>
                    </form>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

donation/templates/all_logins.html
{% load static %}

<html>

<head>

</head>

</html>

<body>
    {% include 'navigation.html' %}
    <hr class="mt-0">
    <div class="container mt-5">
        <h2 class="text-center">Login as</h2>
        <div class="row">
            <div class="col-lg-4">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/businessman-giving-money-donation-to-charity-free-photo.jpg' %}" alt="" class="card-img-top" style="width: 100%; height: 200px;">
                    <div class="card-body">
                        <h4 class="card-title">Donor</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet.</p>
                        <a href="{% url 'donor_login' %}" class="btn btn-primary">Donor login</a>
                    </div>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/getty_501535569_375772.jpg' %}" alt="" class="card-img-top" style="width: 100%; height: 200px;">
                    <div class="card-body">
                        <h4 class="card-title">Charity Foundation</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet.</p>
                        <a href="{% url 'charfo_login' %}" class="btn btn-primary">Charity Foundation login</a>
                    </div>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/windows_uac_shield_logo_hero.jpg' %}" alt="" class="card-img-top" style="width: 100%; height: 200px;">
                    <div class="card-body">
                        <h4 class="card-title">Admin</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet.</p>
                        <a href="{% url 'admin_login' %}" class="btn btn-primary">Admin login</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

donation/templates/charfo_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
</head>
<body style="background-image: url({% static 'images/istockphoto-1278525359-170667a.jpg' %});">
    {% include 'navigation.html' %}
    <hr class="mt-0">
    <div class="row">
        <div class="col-lg-5 m-auto">
            <div class="card mt-5 bg-dark">
                <div class="card-title text-center mt-3">
                    <img src="{% static 'images/2476166.jpg' %}" alt="" width="150" height="150">
                    <h2 style="color: aliceblue;">Charity Foundation Login</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user fa-2x"></i>
                                </span>
                            </div>
                            <input type="email" name="emailid" class="form-control py-4" placeholder="Email Id">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-lock fa-2x"></i>
                                </span>
                            </div>
                            <input type="password" name="pwd" class="form-control py-4" placeholder="password">
                        </div>
                        <input type="submit" value="login" class="btn btn-success px-5">
                        <a href="{% url 'charfo_reg' %}" class="float-right text-white mt-2">Create Account</a>
                    </form>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

donation/templates/charfo_reg.html
{% load static %}

<html>

<head>

</head>

<body>
    {% include 'navigation.html' %}
    <hr class="mt-0">
    <div class="card shadow m-5">
        <div class="card-body ">
            <h5 class="p-2" style="border-bottom: 2px solid orange">Charity Foundation Account</h5>
            <div class="container-fluid">
                <form method="post" enctype="multipart/form-data" name="signup" onsubmit="return checkpassword()">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>First Name</label>
                                <input class="form-control" type="text" name="firstname" placeholder="John" required
                                    pattern="[A-Za-z]+">
                            </div>
                        </div>


                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Last Name</label>
                                <input class="form-control" type="text" name="lastname" placeholder="Doe" required
                                    pattern="[A-Za-z]+">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Email</label>
                                <input class="form-control" type="email" name="email" placeholder="johndoe@gmail.com" required
                                    patter="[A-Za-z]+">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Contact</label>
                                <input class="form-control" type="tel" name="contact" placeholder="+91 99999 99999">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label >Password</label>
                                <input class="form-control" type="password" name="pwd" placeholder="password">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input class="form-control" type="password" name="cpwd">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Userpic</label>
                                <input class="form-control" type="file" name="userpic">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>About your foundation</label>
                                <textarea class="form-control" type="text" name="aboutme"></textarea>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label name="idpic">Upload Aadhar</label>
                                <input class="form-control" type="file" name="idpic" >
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label name="address">Address</label>
                                <textarea class="form-control" type="text" name="address" placeholder="Full address" required
                                    pattern="[A-Za-z]+"></textarea>
                            </div>
                        </div>

                    </div>
                    <input type="submit" value="Submit" class="m-2 px-3 btn btn-primary">
                </form>

            </div>
        </div>

    </div>
    <script>
        function checkpassword(){
            if(document.signup.pwd.value != document.signup.cpwd.value)
            {
                alert('Password must be same.');
                document.signup.cpwd.focus();
                return false;
            }
            return true;
        }
    </script>
    {% if error == "no" %}
    <script>
        alert('Sign up successful')
        window.location=('{% url 'charfo_login' %}')
    </script>
    {% endif %}
    {% if error == "yes" %}
    <script>
        alert('Something went wrong. Try again.')
        window.location=('{% url 'charfo_reg' %}')
    </script>
    {% endif %}
</body>

</html>

donation/templates/donate_now.html
{% extends 'donor_base.html' %}



{% block main %}

<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom : 2px solid orange">Donate Now</h5>
        <div class="container-fluid">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donate Now <span style="color: red">(Mention details if other is
                                    selected)</span></label>
                            <select name="donationname" class="form-control" required>
                                <option value="Clothes Donation">Clothes Donation</option>
                                <option value="Toys Donation">Toys Donation</option>
                                <option value="Furniture Donation">Furniture Donation</option>
                                <option value="Footwear Donation">Footwear Donation</option>
                                <option value="Book Donation">Book Donation</option>
                                <option value="Kitchenware Donation">Kitchenware Donation</option>
                                <option value="Other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donation pic</label>
                            <input type="file" name="donationpic" required class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donation address</label>
                            <textarea name="collectionloc" class="form-control" placeholder="Address" required cols="30"
                                rows="10"></textarea>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Description (Special Note)</label>
                            <textarea name="description" class="form-control" placeholder="Note"></textarea>
                        </div>
                    </div>
                </div>
                <script src="https://checkout.razorpay.com/v1/payment-button.js" data-payment_button_id="pl_HB8hlJynaP4Qzh" async> </script> 
            </form>

        </div>
    </div>
</div>



{% endblock %}

donation/templates/donor_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="{% static 'js/myjs.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <script src="https://kit.fontawesome.com/2e375cc1ab.js" crossorigin="anonymous"></script>
    <title>Donation Page</title>
</head>

<body>
    <style>
        
    </style>
    <div class="vertical-nav bg-white" id="sidebar">
        <div class="py-4 px-3 mb-1bg-light">
            <p class="text-center font-weight-bold text-uppercase px-3 small dashboard-text">
                Donation Management System
            </p>
            <div class="media d-flex align-items-center">
                <img src="{{request.user.donor_set.all.0.userpic.url}}" width="80" height="80" alt="">
                <div class="media-body">
                    <h4 class="mb-0">Donor</h4>
                    <p class="text-muted mb-0">{{ request.user.username }}</p>
                </div>
            </div>
        </div>
        <ul class="nav flex-column bg-white">
            <li class="nav-item">
                <a href="{% url 'donor_home' %}" class="nav-link text-dark bg-light">
                    <i class="fas fa-tachometer-alt fa-fw mr-3 text-primary"></i>
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'donate_now' %}" class="nav-link text-dark bg-light">
                    <i class="fas fa-tachometer-alt fa-fw mr-3 text-primary"></i>
                    Donate Now
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>
                    Services
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Add services</a>
                    <a class="dropdown-item" href="">Manage services</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>
                    Contact Us
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Unread queries</a>
                    <a class="dropdown-item" href="">Read queries</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>
                    Booking
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">New booking</a>
                    <a class="dropdown-item" href="">Old booking</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>
                    Change Password
                </a>

            </li>
        </ul>
    </div>


    <div class="page-content p-4" id="content">
        <a href="{% url 'logout' %}" title="logout" class="float-right text-white"><i class="fa fa-sign-out"></i></a>

        <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill"><i
                class="fas fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Toggle</small></button>

        {% block main %}
        {% endblock %}
    </div>
    <script>
        $(function(){
    $('#sidebarCollapse').on('click',function(){
        $('#sidebar,#content').toggleClass('active');
    });
});
    </script>
</body>

</html>

donation/templates/donor_home.html
{% extends 'donor_base.html' %}

{% block main %}

{% endblock %}

donation/templates/donor_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
</head>
<body style="background-image: url({% static 'images/photo-1488521787991-ed7bbaae773c.jpg' %});">
    {% include 'navigation.html' %}
    <hr class="mt-0">
    <div class="row">
        <div class="col-lg-5 m-auto">
            <div class="card mt-5 bg-dark">
                <div class="card-title text-center mt-3">
                    <img src="{% static 'images/2476166.jpg' %}" alt="" width="150" height="150">
                    <h2 style="color: aliceblue;">Donor Login</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user fa-2x"></i>
                                </span>
                            </div>
                            <input type="email" name="emailid" class="form-control py-4" placeholder="Email Id">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-lock fa-2x"></i>
                                </span>
                            </div>
                            <input type="password" name="pwd" class="form-control py-4" placeholder="password">
                        </div>
                        <input type="submit" value="login" class="btn btn-success px-5">
                        <a href="{% url 'donor_reg' %}" class="float-right text-white mt-2">Create Acccount <i class="fas fa-angle-double-right"></i></a>
                    </form>
                </div>
            </div>
        </div>

    </div>
    {% if error == "no" %}
    <script>
        alert('Sign in successful')
        window.location=('{% url 'donor_home' %}')
    </script>
    {% endif %}
    {% if error == "yes" %}
    <script>
        alert('Invalid credentials. Try again! ')
        window.location=('{% url 'donor_reg' %}')
    </script>
    {% endif %}
</body>
</html>

donation/templates/navigation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mystyle.css'%}">
    <script src="https://kit.fontawesome.com/2e375cc1ab.js" crossorigin="anonymous"></script>
    <title>Donation Page</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <a href="#" class="navbar-brand">
                <img src="" alt="">
                <span style="color: black;">Donation Management System</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="thetarget">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="myMenu">
                <ul class="navbar-nav pl-5 custom-nav ml-auto">
                {% if request.path == '/' %}
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'all_logins' %}" class="nav-link">Login</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Go back to homepage</a></li>
                {% endif %}
                </ul>
            </div>
        </div>

    </nav>
    <script src="{% static 'js/myjs.js' %}"></script>
</body>

</html>